adafruit/Adafruit_CircuitPython_MiniMQTT

examples/minimqtt_adafruitio_wifi.py
Updating Adafruit IO MQTT example to be more inline with the [mqtt_esp8266](https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino) example in the Adafruit MQTT Library for use with a future Learning System Guide.
=> Update Adafruit IO MQTT Example

adafruit_minimqtt.py
The _remaining length_  used by `connect` is incompatible with large payloads (>127 bytes). An instance of this is when a long (> 300 byte) password, such as a JSON Web Token, or a long client identifier is provided.
* The remaining length calculation used by this library has been removed in favor of using the  algorithm described by the MQTT V3.1.1 specification (https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718030).
* Default `keepalive` value sent by `connect()` increased to 60 seconds to ensure the MQTT broker rejects incorrect connections, instead of hanging `_wait_for_msg()`.
* Fixed header bytearray removed, switching to a variable bytearray.
* Variables within `connect` renamed to correct names per the MQTT spec.
Tested with a PyPortal running …
=> Fix CONNECT for large MQTT payloads

adafruit_minimqtt.py
This pull request improves how the library handles the MQTT KeepAlive with the initial CONNECT packet [MQTT-3.1.2-23]. We'll connect to a server, and _stay_ connected.
* `keep_alive` exposed as an init kwarg - different brokers expect different `keeep_alive` values and a user may also want to set this value manually.
* The `loop` method now checks the time and sends a PINGREQ (expecting a PINGRESP, this is handled in the `ping()` method) to the server if the time elapsed is greater than or equal to the provided keepalive value. 
* The `loop_forever` method has been refactored to call `loop` instead of `_wait_for_msg`. This method also now handles network control, for both the socket and the NetworkManager (currently WiFiManager) objects. 
* Properties for network management …
=> Improve network handling and implement time-based KeepAlive

adafruit_minimqtt.py
`rc` reads 3 bytes, not 4. The 3rd byte is the error code, referenced by `CONNACK_ERRORS`
Pre-PR:
```
b'\x02\x00\x05'
Traceback (most recent call last):
File "code.py", line 121, in <module>
File "/lib/adafruit_iotcore/adafruit_iotcore.py", line 121, in connect
File "/lib/adafruit_minimqtt.py", line 284, in connect
IndexError: bytes index out of range
```
Post-PR:
```
4132.02: DEBUG - Receiving CONNACK packet from broker
b'\x02\x00\x05'
Traceback (most recent call last):
File "code.py", line 121, in <module>
File "/lib/adafruit_iotcore/adafruit_iotcore.py", line 121, in connect
File "/lib/adafruit_minimqtt.py", line 284, in connect
MMQTTException: Connection Refused - Unauthorized
```
=> Fix CONNACK IndexError 

adafruit_minimqtt.py
Switching the following private MiniMQTT attributes to public:
* `user`, `keepalive`, `password`, `client_id`, `logger`
These private attributes are used by MiniMQTT client libraries, such as Adafruit IO CircuitPython, for client identification and writing to the logger.
=> Exposing attributes used by client libraries

adafruit_minimqtt.py
Switching `socket.write` to `socket.send` to match the [CircuitPython Socket API](https://circuitpython.readthedocs.io/en/latest/shared-bindings/socket/__init__.html#socket.send) and the [CPython Socket API](https://docs.python.org/3/library/socket.html#socket.socket.send).
Related PR: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/pull/70
=> Switch to Socket.Send

adafruit_minimqtt.py
Switching `socket.read` calls to `socket.recv`.
Related PR: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/pull/71
=> Use socket.recv

examples/minimqtt_certificate.py, minimqtt_certificate.py
Adding usage example for establishing a secure MQTT connection with a server, provided a user-defined X.509 certificate and private key.
**NOTE: This example requires nina-fw v1.4.0 or above.**  If you do not know how to upgrade the firmware on your ESP32, [follow the learn guide on the Adafruit Learning System for this topic](https://learn.adafruit.com/upgrading-esp32-firmware).
Example of usage, connecting to AWS IoT
```
code.py output:
Attempting to connect to GATEWAYNAME-ats.iot.us-east-2.amazonaws.com
Sending connect to broker
32 <--MQTT Auth Accepted by Broker
Connected to MQTT Broker!
Flags: 0
RC: 0
Subscribing to test/topic
```
=> Add example for using MiniMQTT with User-Provided Certificate/Key

adafruit_minimqtt.py
addresses part of  #16
use time.monotonic() instead of microcontroller.cpu.uid for random seed to create client ID
=>  revise generation of client ID

examples/minimqtt_pub_sub_pyportal
This example shows how to get miniMQTT to work with the PyPortal library.
=> Example for using miniMQTT with the PyPortal

examples/minimqtt_adafruitio_wifi.py
Removes `debug=True` parameter in AIO wifi post example, no other examples contain a debug kwarg.
=> Remove esp debug kwarg in AIO post example

examples/minimqtt_adafruitio_cellular.py, examples/minimqtt_simpletest_cellular.py
Adding examples for using this library with a cellular (https://github.com/adafruit/Adafruit_CircuitPython_FONA/pull/3) interface.
=> Add cellular usage examples

adafruit_minimqtt.py, examples/minimqtt_adafruitio_cellular.py, examples/minimqtt_adafruitio_eth.py, examples/minimqtt_adafruitio_wifi.py, examples/minimqtt_simpletest_cellular.py
Fixes https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/25
* Broker does not need HTTP/HTTPS URL since MQTT brokers will never start with `http://` or `https:/`
* Removed try/except block which improperly handles IP address strings
* Removed of `TCP_Mode`/`TLS_Mode` in favor of using the interface's tcp or tls mode.
Examples which need to be update to reflect this change
https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/pull/12
=> Fix Hostname Issue (#25)

examples/minimqtt_adafruitio_cellular.py, examples/minimqtt_simpletest_cellular.py
Updated cellular examples for breaking FONA library release (v2.0.0), https://github.com/adafruit/Adafruit_CircuitPython_FONA/releases/tag/2.0.0
output:
```
code.py output:
Attaching to network...
Attaching to network...
Attaching to network...
Attached!
Connecting to network...
Connecting to network...
Network Connected!
Connecting to Adafruit IO...
Connected to Adafruit IO! Listening for topic changes on brubell/feeds/onoff
Sending photocell value: 0...
Sent!
New message on topic brubell/feeds/onoff: ON
Sending photocell value: 1...
Sent!```
=> Updated Cellular Examples

adafruit_minimqtt.py
This pull request addresses the issues in https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/35
* `last_will` method renamed to `will_set`, kwargs renamed to mirror Paho-MQTT 
* Call to `self.last_will()` removed in `__init__`. Instead, set LWT properties.
* Payload data converted to bytes for usage in `connect`
Tested on: 
`Adafruit CircuitPython 5.3.0 on 2020-04-29; Adafruit Feather Bluefruit Sense with nRF52840`
Code Tested:
```
import time
import board
import busio
from digitalio import DigitalInOut
import neopixel
from adafruit_esp32spi import adafruit_esp32spi
from adafruit_esp32spi import adafruit_esp32spi_wifimanager
import adafruit_esp32spi.adafruit_esp32spi_socket as socket
import adafruit_minimqtt as MQTT
try:
from secrets import secrets
except ImportError: …
```
=> Fix LWT Issues

LICENSE, adafruit_minimqtt/adafruit_minimqtt.py, adafruit_minimqtt/matcher.py, docs/api.rst, examples/minimqtt_pub_sub_blocking_topic_callbacks.py, examples/minimqtt_pub_sub_multiple_callbacks.py
Addresses issue: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/37
* Adds `add_topic_callback`: Registers a callback_method for a specific MQTT topic.
* Adds `remove_topic_callback`: Removes a registered callback method
* Setting `on_message = callback_method` from user_code is performed using a getter/setter.
* `MQTTMatcher`, MQTT topic format matcher added from Eclipse Paho MQTT https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/matcher.py
* Licensing updated to reflect new code.
--- 
Tested using: `examples/minimqtt_pub_sub_blocking_topic_callbacks.py`
Tested on: `Adafruit CircuitPython 5.3.0 on 2020-04-29; Adafruit Feather Bluefruit Sense with nRF52840` with AirLift FeatherWing
REPL output
```
code.py output:
Connecting to WiFi...
Connected! …
```
=> Add Topic-specific message callbacks 

examples/minimqtt_adafruitio_cellular.py, examples/minimqtt_adafruitio_eth.py, examples/minimqtt_adafruitio_wifi.py, examples/minimqtt_certificate.py, examples/minimqtt_pub_sub_blocking.py, examples/minimqtt_pub_sub_blocking_topic_callbacks.py, examples/minimqtt_pub_sub_nonblocking.py, examples/minimqtt_pub_sub_pyportal.py, examples/minimqtt_simpletest.py, examples/minimqtt_simpletest_cellular.py, examples/minimqtt_simpletest_eth.py
Addresses https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/40
This pull request:
* Changes import statements in code examples to reflect the library's modified path in release `3.1.0`
=> Fix import path in examples

adafruit_minimqtt/adafruit_minimqtt.py, docs/examples.rst
I went to read the docs for this library and noticed all the parameters and example code-blocks were not displaying properly because there was no empty line that preceded them. Verified locally via `sphinx-build` that the changes generate properly.
Upon further reading I noticed there was a (un-admonished) deprecation notice and a reference to an example that was not being displayed on RTD. I added the example to `examples.rst` as "Basic Forever Loop", and I changed the notice to an admonished "Note" so that it sticks out to the reader better.
Side-note: there are a lot more examples in this library that are not being displayed on RTD. Furthermore there are no module-level docstrings that would help identify the purpose of the examples (other than the example filename). I'm not too …
=> api doc's param & code-block display correctly

adafruit_minimqtt/adafruit_minimqtt.py
satisfies #39 in accordance with paho_mqtt library compatibility
I tested this fix locally (on my trusty ItsyBitsy M4) without connection to a broker. The only esp32 I have lying around is a TinyPico, so properly testing this on my end might be a bit taxing for a 1-line fix. If there's an easier way to test this with a Raspberry Pi, I'd gladly dust off my old RPi.
I followed the data from the `payload` parameter through the code to see if this fix instigates another issue, and I found no problems. However, I'm not sure about `self._sock.send(string)` where `self._lw_msg` (instance attribute that holds the zero-length string when payload parameter is of type `None`) is passed as the `string` parameter in [`_send_str()`](https://github.com/2bndy5/Adafruit_CircuitPython_MiniMQTT/blob/95f95193 …
=> payload parameter of type `None` replaced with zero-length string in `will_set()`

adafruit_minimqtt/adafruit_minimqtt.py
@brentru This should now be rebased upon the adafruit master branch.
changes include:
* removed deprecated `loop_forever()` in preparation for next major release.
* consolidated the `fixed_header` initialization to 1 line of code.
=> adjust fixed_header init; (-) loop_forever()

README.rst, adafruit_minimqtt/adafruit_minimqtt.py, adafruit_minimqtt/matcher.py
```python
Adafruit CircuitPython 5.0.0-beta.0-2634-gda61845f5-dirty on 2020-08-24; FeatherS2 with ESP32S2
>>> import os
>>> os.listdir('/lib')
['adafruit_requests.mpy', 'adafruit_azureiot', '._adafruit_azureiot', 'adafruit_minimqtt', '._adafruit_minimqtt', 'adafruit_binascii.mpy', '._adafruit_binascii.mpy', 'adafruit_ntp.mpy', '._adafruit_ntp.mpy']
>>> import adafruit_minimqtt.adafruit_minimqtt as MINIQTT
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "adafruit_minimqtt/adafruit_minimqtt.py", line 47, in <module>
ImportError: no module named 'adafruit_logging'
```
=> Adafruit Logging is required

adafruit_minimqtt/adafruit_minimqtt.py
This change addresses a few issues in the handling of the MQTT
messages that caused the library to become unstable:
- Add wapper for socket.recv() so that an exact number of bytes
are read into the buffer before attempting to parse the MQTT
message;
- Fix handling of ping response packets via _wait_for_msg();
- Fix disconnect so it can gracefully handle cases when socket writes
are not possible. Also re-init _subscribed_topics as an empty list
instead of None.
Related-to https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/issues/102
Fixes https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/issues/98
Fixes https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/54
Signed-off-by: Flavio Fernandes <flavio@flaviof.com>
=> Fix socket receive issues related to message buffer size

adafruit_minimqtt/adafruit_minimqtt.py
Have been having a discussion with @brentru about an issue with the esp32spi implementation of `loop()` always blocking until the end of the keepalive period. We think raising `OSError(errno.ETIMEDOUT)` at the right point may fix that issue. Also replaces some `%x` format codes with `%s` in the logging statements because `bytearray`s can't be formatted with `%s`. (The `%s` is ugly but it works.)
=> Make loop() in esp32spi implementation non-blocking

.github/workflows/build.yml, adafruit_minimqtt/adafruit_minimqtt.py, examples/cpython/minimqtt_simpletest_cpython.py
This pull request:
* Sets `_FakeSSLContext` within calls to `set_interface` instead of within `__init__`
* Removes socket reuse code mirrored in from `adafruit-circuitpython-requests` 
* Calls to `reconnect` now close an open socket
* Legacy socket API set up in `_get_connect_socket` instead of within `__init__`
* Updated `examples/cpython/minimqtt_simpletest_cpython` to address #62 
Addresses https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/62
Tested on: ESP32SPI (PyPortal), CPython, and ESP32-S2 (Metro ESP32-S2)
=> Fix CPython/Legacy Socket SSL Problems

adafruit_minimqtt/adafruit_minimqtt.py
While ESP32-SPI's socket validates if a user passes an invalid port value:
```
code.py output:
Connecting to WiFi...
Connected!
Connecting to Adafruit IO...
Traceback (most recent call last):
File "code.py", line 105, in <module>
File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 437, in connect
File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 240, in _get_connect_socket
File "/lib/adafruit_esp32spi/adafruit_esp32spi_socket.py", line 42, in getaddrinfo
RuntimeError: Port must be an integer
```
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/76 found that native socketpool does not validate port data type before connecting. When entering the port # in the `secrets.py` file, it may be not clear to people that `port` requires an integer value while most other …
=> Validate port is integer type for SocketPool

adafruit_minimqtt/adafruit_minimqtt.py
Publishing with QOS 1 seemed to be broken because PID was incremented immediately *after* putting into packet, meaning that the PUBACK packet would not match the new (incremented) PID.
There is a danger if publishing more than 0xFFFF packets that .to_bytes will fail because it can't pack into 2 bytes after that. PID must wrap around to 1, not 0, according to spec, which demands that PID be nonzero for QOS 1 and 2.
=> MQTT QOS=1,2 rules state that pid must be > 0.

adafruit_minimqtt/adafruit_minimqtt.py
Useful for educational purposes such as serialization/encoding. (protobuf with minipb)
=> Allow publishing of bytes messages

adafruit_minimqtt/adafruit_minimqtt.py
If I set timeout to zero there is a problem as the poll() call will be
called multiple times while a ping request is outstanding and this
results in multiple ping requests being made. I see 3-5 at a time with
DEBUG logging on.
This is because self._timestamp is being reset after self.ping()
The solution seems to be pretty straightforward which is to reset
self._timestamp() before sending the ping()
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>
=> adafruit_minimqtt: Fix issue #86 with multiple poll() PINGREQs

adafruit_minimqtt/adafruit_minimqtt.py
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/90#issue-981092769
I override the default len() method. Now, when calculating the length of a string, it will return the length of the UTF-8 encoded bytes instead of the number of characters.
This change will not affect the calculation of English string length. However, when dealing with certain languages, it helps a lot.
For example, "中文" in UTF-8 encoded bytes is "\xe4\xb8\xad\xe6\x96\x87". Previously, len("中文") is 2 (incorrect). After override, len("中文") is 6 (len(b'\xe4\xb8\xad\xe6\x96\x87'), correct).
Because there are too many uses of len(str) in the code, I carried out this override to fix them at a time. After confirming that the issue I raised is valid, maybe you can have a more professional and elegant way to fix …
=> Fix Issue #90: Remaining length issues

adafruit_minimqtt/adafruit_minimqtt.py
I'm creating a basic client library to use with [Golioth](https://golioth.io) Platform. We recently added a new gateway to support MQTT devices and that allows us to add support to CircuitPython.
But while developing the client, we had issues with one of our services meant for Over the Air Updates, which serves not only for the main device firmware, but you can send any arbitrary artifact ( like images/bitmap in my testing here). Currently, this MQTT library tries to convert all messages to a Unicode string, which unfortunately fails for binary data. Reference to where it fails: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/main/adafruit_minimqtt/adafruit_minimqtt.py#L843
So what I'm proposing here is to add an optional parameter called `use_binary`, that would allow …
=> feat: add support for binary messages

adafruit_minimqtt/adafruit_minimqtt.py
In the documentation for adafruit_minimqtt at https://circuitpython.readthedocs.io/projects/minimqtt/en/latest/api.html, the :param information in the class docstring and several method docstrings is run into the description rather than being neatly formatted. This fix only adds blank lines as necessary to enable more readable formatting.
=> Added missing blank lines before :param blocks in docstrings

adafruit_minimqtt/adafruit_minimqtt.py
May also fix the error resulting in #102 by re-running the CI.
=> Minor updates to documentation

adafruit_minimqtt/adafruit_minimqtt.py
writes topic and raw message when loop receives a message from a subscribed topic, when debug is enabled.
=> add debug logging to recieved messages.

adafruit_minimqtt/adafruit_minimqtt.py
This change allows to set socket timeout via the init function, like so:
```python
mqtt_client = MQTT.MQTT(
broker=secrets["broker"],
port=secrets["broker_port"],
socket_pool=pool,
ssl_context=ssl.create_default_context(),
socket_timeout=3,
)
```
I verified with `strace` that the `poll()` syscall timeout value reflects the `socket_timeout` parameter.
=> allow to set socket timeout

adafruit_minimqtt/adafruit_minimqtt.py
This change introduces receive timeout so that functions that wait for data from a broker have some upper bound.
Tested on Python 3.9.2 on Raspbian with a remote that accepts any data however does not send anything back (Netcat in plain listen mode).
Thinking of the interaction with the changes in PR #116, it might be prudent to raise `RuntimeError` in the init function if the receive timeout is bigger than the socket timeout.
=> avoid endless loop when waiting for data from broker

adafruit_minimqtt/adafruit_minimqtt.py
This change exposes retry count to MQTT class init.
=> make connect retries configurable

adafruit_minimqtt/adafruit_minimqtt.py
You get EAGAIN when passing a timeout value of 0 and there is no data in the buffer.
=> _wait_for_msg(): accept EAGAIN in addition to ETIMEDOUT

adafruit_minimqtt/adafruit_minimqtt.py
First PR, so bear with me!
Basically, I've found issues with callling `loop()` too frequently or too infrequently, that I'm trying to address here.
Calling too frequently (with timeout >0) can lead to a nasty MemoryError. https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/101
Calling too infrequently can cause a build up of messages on the broker. https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/108
I've changed the default timeout to 0 (and added error handling of EAGAIN)
This might be a controversial change - but it means the function is really non-blocking as the comments say it should be. (Perhaps there is a history of why it was set to 1 by default?, I'd be happy keeping it at 1 if it prevents issues for others)
I've also made it call …
=> Fetch all messages in loop, non-blocking mode

adafruit_minimqtt/adafruit_minimqtt.py
closes #109 
Renamed original is_connected method to _connected to maintain internal connection status checking. Created a new is_connected function that returns a bool. This is a breaking change.
This change allows code to be written like:
```
while not mqtt_client.is_connected():
try:
mqtt_client.connect()
except RuntimeError:
print("Unable to connect. Waiting for 10 seconds before retrying…")
time.sleep(10)
print("Connected to MQTT broker.")
```
=> Changed is_connected to return bool while maintaining error checking

adafruit_minimqtt/adafruit_minimqtt.py
Added bytearray('\x00') to the list of expected "noop" returns from the socket.
=> Issue #126

adafruit_minimqtt/adafruit_minimqtt.py
This is API-breaking, but hopefully makes using the library less prone to errors.  I couldn't find any existing libraries or Learn Guides (save for one that's already broken with regards to API since it hasn't been updated for the last API-breaking change to `MQTT.__init__()`).
Resovles #120
=> Make MQTT__init__ arguments keyword-only

adafruit_minimqtt/adafruit_minimqtt.py
Connect needs to distinguish None from an empty string when populating and sending CONNECT to the MQTT broker.
Fixes #129
Signed-off-by: Flavio Fernandes <flavio@flaviof.com>
=> MQTT connect with an empty username should have the proper header

adafruit_minimqtt/adafruit_minimqtt.py
I noticed that the documentation for `enable_logger()` talks about logger object, while it actually means logging package to create/retrieve the logger. While there I added the possibility to change logger name because by default such generic name was used so it might conflict with a logger created before interacting with `adafruit_minimqtt` (also given how logger creation in `adafruit_logging` works).
While there, I made the function return the logger object, in case someone wants to further change it (e.g. add handlers). I did this because `self.logger` is not preceded with `_` so probably not considered private.
=> use correct terminology for enable_logger()

adafruit_minimqtt/adafruit_minimqtt.py
When experimenting with TLS based connections to various ports on https://test.mosquitto.org/ , I found that the 8883 value is hard-coded. This change replaces the values with the global const. This does not fix the issue with specifying arbitrary port as TLS port, it merely straightens the use of global constant.
=> do not hard-code TLS port value

adafruit_minimqtt/adafruit_minimqtt.py
This change allows to set the opaque user data in the init method. Works like this:
```python
"""
MQTT utility functions
"""
import ssl
import adafruit_logging as logging
import adafruit_minimqtt.adafruit_minimqtt as MQTT
def connect(mqtt_client, userdata, flags, rc):
"""
This function will be called when the mqtt_client is connected
successfully to the broker.
"""
logger = userdata
logger.info("Connected to MQTT Broker!")
logger.debug(f"Flags: {flags}\n RC: {rc}")
def disconnect(mqtt_client, userdata, rc):
"""
This method is called when the mqtt_client disconnects from the broker.
"""
logger = userdata
logger.info("Disconnected from MQTT Broker!")
def publish(mqtt_client, userdata, topic, pid):
"""
This method is called when the mqtt_client publishes data to a feed.
"""
logger = userdata …
```
=> allow to set user data in the init method

adafruit_minimqtt/adafruit_minimqtt.py
This change addresses the problem of returning incomplete buffer from _sock_exact_recv() in CPython.
Tested with:
```python
#!/usr/bin/env python3
import adafruit_minimqtt.adafruit_minimqtt as MQTT
import socket
import ssl
import logging
def connect_hook(client, user_data, result, code):
print(f"Connect: {user_data} {result} {code}")
def message_hook(client, topic, message):
print(f"Message: topic='{topic}' message='{message}'")
broker = "test.mosquitto.org"
port = 1883
mqtt_client = MQTT.MQTT(
broker=broker,
port=port,
socket_pool=socket,
ssl_context=ssl.create_default_context(),
)
logging.basicConfig()
mqtt_client.on_message = message_hook
mqtt_client.connect()
mqtt_client.subscribe('#')
while True:
try:
mqtt_client.loop(5)
except UnicodeDecodeError:
pass
```
It survived the wild …
=> make sure to read the whole buffer in _sock_exact_recv()

adafruit_minimqtt/adafruit_minimqtt.py
There is no such argument as `network_manager` in `MQTT()` so this change updates the doc string.
=> remove unused doc reference to network manager

adafruit_minimqtt/adafruit_minimqtt.py
=> use f-strings where possible

adafruit_minimqtt/matcher.py
This change approaches #92, specifically for `matcher.py`. After that `mypy` complains only about the function parameters/assignment:
```
$ mypy --strict adafruit_minimqtt/matcher.py 
adafruit_minimqtt/matcher.py:50: error: Incompatible types in assignment (expression has type "Callable[..., Any]", variable has type "None")  [assignment]
adafruit_minimqtt/matcher.py:100: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[..., Any]")  [assignment]
Found 2 errors in 1 file (checked 1 source file)
```
This is my first time adding type hints to Python code and have to say, being used to strongly typed language, that it feels a bit strange - retrofitting type specification that is still limping, e.g. the case of `None` or missing function type …
=> add type hints to matcher.py

adafruit_minimqtt/adafruit_minimqtt.py
This change implements exponential back-off for connect/reconnect based on the Google IoT algorithm description (sic!), with a nuance in handling temporary errors (like name resolution errors or memory shortage). At one point I had code that applied the exponential back-off also for successfull reconnect()s, however found it a bit too complex and hand-holdy. If one calls reconnect() in a loop even after prior successful connect without sleeping in between, he probably deserves to be rate limited by the broker.
=> exponential backoff for (re)connect

adafruit_minimqtt/adafruit_minimqtt.py
As mentioned in https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/150#issuecomment-1429391988 the logger check is error prone.
=> add missing logger check

adafruit_minimqtt/adafruit_minimqtt.py, examples/cpython/minimqtt_adafruitio_cpython.py, examples/ethernet/minimqtt_simpletest_eth.py, examples/native_networking/minimqtt_adafruitio_native_networking.py, tests/test_port_ssl.py, tox.ini
Instead of using the `MQTT_TLS_PORT` value as indication whether TLS should be used, this change introduces private field that is set based on the `MQTT()` `is_ssl` argument.
The downside of this approach is that if someone specifies `port=1883` explicitly without setting `is_ssl` to False, the port will be treated as TLS port since the `is_ssl` is True by default and `OSError("Failed SSL handshake")` will be thrown, unless the broker is configured to accept TLS on that port. I have not made my mind yet whether to special case it and force to insecure so leaving it open for the reviewers.
=> allow to use any port as TLS port

adafruit_minimqtt/adafruit_minimqtt.py
This change removes `_recv_into()`. It was initially introduced in 8492a58f88465148268546fd58712c41208dee6c, then actually used in 2ae61a459dd2842981a15b63f0e60c0a84646749 and then the call was removed in ea966339379c8081dba94c95bd1f286dfe4dcca1.
=> _recv_into() is not used anymore

.gitignore, tests/backoff_test.py, tox.ini
This change adds very rudimentary test for the recently introduced exponential back-off, a tiny piece for #64.
=> add basic back-off test

adafruit_minimqtt/adafruit_minimqtt.py
As explained in https://github.com/adafruit/circuitpython/issues/7606, the SUBACK/UNSUBACK deserves more robust handling.
=> handle variable payload in SUBACK

adafruit_minimqtt/adafruit_minimqtt.py
This change adds more type annotations. `mypy --strict adafruit_minimqtt/adafruit_minimqtt.py` currently below 100 errors (down from 168).
Approaches #92.
=> add some type annotations to adafruit_minimqtt.py

examples/native_networking/minimqtt_adafruitio_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_topic_callbacks_native_networking.py
Add examples using cert/key pair to address https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/98
=> Add examples using cert/key pair

examples/esp32spi/minimqtt_adafruitio_esp32spi.py, examples/esp32spi/minimqtt_pub_sub_blocking_esp32spi.py, examples/esp32spi/minimqtt_pub_sub_nonblocking_esp32spi.py, examples/esp32spi/minimqtt_simpletest_esp32spi.py, examples/minimqtt_simpletest.py, examples/native_networking/minimqtt_adafruitio_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_topic_callbacks_native_networking.py
hihi @brentru - I updated the examples that are in the MiniMQTT guide to use settings.toml. Had to change up the WiFi connection method for ESP32SPI since adafruit_esp32spi_wifimanager assumes secrets is being used. Tested native networking with a QT Py ESP32-S2 and ESP32SPI with a Metro M7.
if you are good with how these are formatted I can update the other examples as well.
=> Settings dot toml

adafruit_minimqtt/adafruit_minimqtt.py, examples/esp32spi/minimqtt_pub_sub_nonblocking_esp32spi.py
This changes the way how loop() deals with the timeout parameter. I think the original idea was to wait for the timeout and then return what was received in the mean time, regardless of whether anything was actually received. This means that the loop() will always return after the timeout, i.e. not earlier (assuming no fatal error happened).
Inspired by https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/68#issue-805498443 and the discussion in PR #168.
=> loop() timeout parameter should be absolute

tests/test_loop.py
Since finishing PR #169, I have been thinking about at least simple test for the loop() return semantics. Here it is.
There is some room for improvement (like always). Specifically, there are other aspects of the function that could be tested (such as MQTT ping) and also if loop() was not cooperating (by returning within some time), the test would be hosed.
=> add basic loop() test

adafruit_minimqtt/adafruit_minimqtt.py
=> no need to pass self to _handle_on_message()

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_loop.py
[Someone hit a None-deref](https://forums.adafruit.com/viewtopic.php?t=203980) when calling `loop()` without calling `connect()` first. This change checks the connected status in loop() and raises exception if not connected.
=> check is_connected in loop()

adafruit_minimqtt/adafruit_minimqtt.py, examples/cpython/user_data.py
This change makes using `user_data` more accessible for received message callbacks.
=> make user_data "public"

adafruit_minimqtt/adafruit_minimqtt.py
This change will use `time.monotonic_ns()` if available to provide monotonic time based counter with consistent precision in order to be able to work for longer periods of time. On systems that lack this API the `__init__()` init will throw `MMQTTException` unless the `use_imprecise_time` is set to True to avoid unpleasant surprises when running for days on end.
At this stage this is being offered for discussion. Once an approach is found suitable, I will perform testing on HW.
=> use time.monotonic_ns() when available

adafruit_minimqtt/adafruit_minimqtt.py
While traversing the `_wait_for_msg()` code, I noticed that there is discrepancy between what the docs say about the return value and reality. This change fixes that.
=> _wait_for_msg() should return message type

adafruit_minimqtt/adafruit_minimqtt.py
This straightforward change prevents unwanted reuse of certain fields in the CONNECT variable header. Another way to fix this would be to use `copy.copy()` however that does not seem to be present in CP.
=> do not share CONNECT variable header

adafruit_minimqtt/adafruit_minimqtt.py, tests/mocket.py, tests/test_subscribe.py, tests/test_unsubscribe.py
This change fixes remaining length encoding for SUBSCRIBE packets, allowing subscribe to pass for remaning length bigger than 127. Tested on CPython with:
```python
#!/usr/bin/env python3
import json
import socket
import ssl
import sys
import adafruit_minimqtt.adafruit_minimqtt as MQTT
import logging
def main():
logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.info("Creating MQTT instance")
broker = "172.40.0.3"
port = 1883
mqtt_client = MQTT.MQTT(
broker=broker,
port=port,
socket_pool=socket,
ssl_context=ssl.create_default_context(),
connect_retries=3,
)
mqtt_client.enable_logger(logging, log_level=logging.DEBUG)
logger.info("Connecting to MQTT broker")
mqtt_client.connect()
topics = …
```
=> encode/decode remaining length properly for {,UN}SUBSCRIBE/SUBACK

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_loop.py
The `timeout` argument of `loop()` depends on the socket timeout. With some extra debug logging:
```diff
diff --git a/adafruit_minimqtt/adafruit_minimqtt.py b/adafruit_minimqtt/adafruit_minimqtt.py
index 2ec0100..98f68cf 100644
--- a/adafruit_minimqtt/adafruit_minimqtt.py
+++ b/adafruit_minimqtt/adafruit_minimqtt.py
@@ -1074,12 +1074,16 @@ class MQTT:
try:
res = self._sock_exact_recv(1)
except self._socket_pool.timeout:
+                self.logger.debug(f"socket timeout [1]: {self.get_monotonic_time()}")
return None
else:  # socketpool, esp32spi
try:
res = self._sock_exact_recv(1)
except OSError as error:
if error.errno in (errno.ETIMEDOUT, errno.EAGAIN):
+                    self.logger.debug(
+                        f"socket timeout [2]: {self.get_monotonic_time()}"
+ …
```
=> enforce loop timeout to be bigger than socket timeout

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_loop.py
This changes the way how pings are treated. Rather than sending PINGREQ based on how `loop()` is called, it is based on how messages are sent to the broker (in accordance with the MQTT spec). Also, the ping handling was folded into the loop in `loop()` to make it work in cases with loop timeouts longer than the keep alive timeout.
I plan to test this on a QtPy.
=> improve ping handling

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_port_ssl.py
The purpose of this PR is to simplify socket exceptions, so the move to [ConnectionManager](https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager) is smother.
Currently when getting a socket, an `OSError` is not treated as a `TemporaryError` and thus the retry is delayed. As far as I can tell, there is no benefit to delaying the next try here and it will cause `ConnectionManager` to be overly complex.
This treats `OSError` like any other error, and thus no custom handling will be needed in `ConnectionManager`.
If there is something I am missing, please let me know.
=> Simplify socket exceptions

examples/native_networking/minimqtt_adafruitio_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_topic_callbacks_native_networking.py
Add `timeout` value to avoid `MMQTTException: loop timeout (0) must be bigger than socket timeout (1))` error.
=> Add `timeout` value.

adafruit_minimqtt/adafruit_minimqtt.py
Fixes https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/207
=> Change free_socket to close_socket

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_backoff.py
Update connection code to break out of the retry look when getting either a `Incorrect username/password` or `Unauthorized` response.
Noticed in #211, although doesn't fix the original post
Tested on a `UM FeatherS3`
=> Don't retry when MQTT response is unauthorized

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_recv_timeout.py
This logical change uses `recv_timeout` as receive timeout in ` _sock_exact_recv()`.
Casually tested with CPython using the test case supplied in the bug, more testing will follow.
=> honor recv_timeout in _sock_exact_recv() and ping()

adafruit_minimqtt/adafruit_minimqtt.py
Final PR in a set. Updating comments in code for what networking modules go down what path to help when troubleshooting.
Updates from:
https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/pull/163
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/pull/206
=> Update comments specific to networking modules

adafruit_minimqtt/adafruit_minimqtt.py
This PR fixes a few things (although the changes are tiny):
fixes #215
`After pystack limit reached, MQTT service continues retry until timeout`
Added a catch for the `RuntimeError: pystack exhaustet` to stop retrying
This also fixes https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT/issues/23
`AWS_IOT_ERROR ('Error Connection to AWS IoT: ', MQTTException('Repeated connect failures',))`
fixes #214
`generic timeout error when 'is_ssl' param not set for an mqtt service that requires it`
This is fixed also by https://github.com/adafruit/circuitpython/pull/9266
Together these provide better errors so the use knows what's happening
=> pystack and other errors

adafruit_minimqtt/adafruit_minimqtt.py
This fixes two related problems which made reconnecting not work after
the connection to the server gets dropped unexpectedly.
The MQTT client continues sending messages and on ESP32 eventually an
OSError is raised. The client must then reconnect. But reconnect was
failing because the Adafruit Connection Manager was returning the same
broken socket for the server since it hadn't yet been closed by
MiniMQTT.
Explicitly calling disconnect() would also not close the socket because
it tries to send the disconnect packet on the broken socket which raised
an OSError preventing the socket from being closed.
=> Close the socket when there is an error using the socket

adafruit_minimqtt/adafruit_minimqtt.py
@ladyada 
Resolves: #227 
Solution discussed with @brentru on discord. I did try changing the cpython examples to use 0, but that still leads to the exception being raised about being shorter than the socket timeout, so I've left them alone in this PR.
=> timout 1 instead of 0

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_recv_timeout.py
- Fixes #230.
The library was using `socket.send()` directly, but not checking the return value to see if all the bytes were sent. So for larger packets, a partial send would go unnoticed. Added `_send_bytes()`, which calls `send()` until all bytes are sent, and also handles `EAGAIN`. I could have used `socket.sendall()`, but it doesn't handle EAGAIN.
I tested by sending 2900-byte packets to a no-history Adafruit IO test feed. @manchicken, who submitted #230, also tested.
=> handle partial socket send()'s

adafruit_minimqtt/adafruit_minimqtt.py
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/commit/75f384545d7590c0d92594cc450c97238d27874b added code for `_send_bytes()` with incomplete reference to `EAGAIN`. This change fixes that.
=> fix EAGAIN reference in _send_bytes()

adafruit_minimqtt/adafruit_minimqtt.py
- Fixes #234.
#231 assumed `Socket.send()` was going to return an int, as it does in CPython. The ESP32SPI version does not :frowning_face: . Thanks @baldengineer and @axelmagnus for testing.
=> Handle ESP32SPI Socket.send(), which does not return a byte count

adafruit_minimqtt/adafruit_minimqtt.py
When attempting to unsubscribe from a topic it was possible to receive the following error:
`Traceback (most recent call last):
File "code.py", line 79, in <module>
File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 869, in unsubscribe
MMQTTException: ('invalid message received as response to UNSUBSCRIBE: 0x30', None)
`
This is due to the unsubscribe function assuming the next packet received will either be the UNSUBACK or an error code, rather than accounting for possible PUBLISH packets coming from the MQTT broker that may have already been in flight. Looking at some packet captures taken from the broker side its possible to get this error before the broker even receives the UNSUB request.
This fix essentially sets the unsubscribe function to match the existing behavior in the …
=> Resolve race condition for UNSUBACK

tests/test_unsubscribe.py
This is a follow-up to PR #225
=> add test for the PUBLISH+UNSUBACK case

adafruit_minimqtt/adafruit_minimqtt.py
I believe the zero byte check in `_wait_for_msg()` can be removed as the issue was present in 8.x releases while we are now safely into 9.x territory.
Related: #237
=> no need to check zero byte returned from recv_into()

tests/test_recv_timeout.py
There's a small interval in `test_recv_timeout.py` of how long to wait for a response. This was first 0.1 seconds, then 0.2, and then that failed too, by a whisker: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/236#issuecomment-2600877237. This increases the wait to half a second.
=> increase test_recv_timeout delay

.pre-commit-config.yaml, adafruit_minimqtt/adafruit_minimqtt.py, examples/cellular/minimqtt_adafruitio_cellular.py, examples/cellular/minimqtt_simpletest_cellular.py, examples/cpython/minimqtt_adafruitio_cpython.py, examples/cpython/minimqtt_simpletest_cpython.py, examples/esp32spi/minimqtt_adafruitio_esp32spi.py, examples/esp32spi/minimqtt_certificate_esp32spi.py, examples/esp32spi/minimqtt_pub_sub_blocking_esp32spi.py, examples/esp32spi/minimqtt_pub_sub_blocking_topic_callbacks_esp32spi.py, examples/esp32spi/minimqtt_pub_sub_nonblocking_esp32spi.py, examples/esp32spi/minimqtt_pub_sub_pyportal_esp32spi.py, examples/esp32spi/minimqtt_simpletest_esp32spi.py, examples/ethernet/minimqtt_adafruitio_eth.py, examples/ethernet/minimqtt_simpletest_eth.py, examples/minimqtt_simpletest.py, examples/native_networking/minimqtt_adafruitio_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_native_networking.py, examples/native_networking/minimqtt_pub_sub_blocking_topic_callbacks_native_networking.py, ruff.toml, tests/test_loop.py, tests/test_port_ssl.py, tests/test_subscribe.py, tests/test_unsubscribe.py
Remove usage of secrets and more:
1. change from using `secrets.py` to `os.getenv`
2. switch from `ESPSPI_WiFiManager` to `WiFiManager`
3. update pool, ssl_context setting to use `adafruit_connection_manager` like all the other examples
4. Updated some things to use f-strings
=> Remove secrets usage

adafruit_minimqtt/adafruit_minimqtt.py, tests/test_loop.py
This changes some of the exceptions raised. Namely it reduces the use of `MMQTTException` to non-programming errors. For these, I converted the code to use `ValueError`/`NotImplementedError` or the newly introduced `MMQTTStateError` (which can be caught via `MMQTTException`).
=> reduce the use of MMQTTException

adafruit_minimqtt/adafruit_minimqtt.py, tests/conftest.py, tests/test_reconnect.py
This change restores the behavior of disconnecting on `reconnect()` if already connected.
=> reconnect restoration

adafruit_minimqtt/adafruit_minimqtt.py
This fixes raising a `MMQTTException` with no argument, raising a `TypeError`, when it [requires an `error` argument](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/6b0f92f8f4a76d8b8431bd21d2656f13dd4b6ed8/adafruit_minimqtt/adafruit_minimqtt.py#L105), as reported in #248 
```
Traceback (most recent call last):
File "adafruit_minimqtt/adafruit_minimqtt.py", line 1036, in _wait_for_msg
File "adafruit_minimqtt/adafruit_minimqtt.py", line 1124, in _sock_exact_recv
File "adafruit_esp32spi/adafruit_esp32spi_socketpool.py", line 171, in recv_into
File "adafruit_esp32spi/adafruit_esp32spi_socketpool.py", line 198, in _available
File "adafruit_esp32spi/adafruit_esp32spi.py", line 892, in socket_available
File "adafruit_esp32spi/adafruit_esp32spi.py", line 431, in …
```
=> Fix missing parameter in MMQTTException
